const type = {
  LOGIN_USER: 'LOGIN_USER',
  SET_USERS: 'SET_USERS',
  SET_JOBS: 'SET_JOBS',
  CREATE_ADMIN: 'CREATE_ADMIN',
  SET_USERS_CARD: 'SET_USERS_CARD',
  SET_CATEOGORIES: 'SET_CATEOGORIES',
  ADD_CATEGORY: 'ADD_CATEGORY',
  SEARCH_QUERY: 'SEARCH_QUERY',
  SEARCH_ERROR: 'SEARCH_ERROR',
  SEARCH_RESULT: 'SEARCH_RESULT',
  SEARCH_FREELANCE: 'SEARCH_FREELANCE',
  SEARCH_JOBS: 'SEARCH_JOBS',
  SEARCH_START: 'SEARCH_START',
  SEARCH_END: 'SEARCH_END',
  SEARCH_CANCEL: 'SEARCH_CANCEL',
  SET_TRANSACTIONS: 'SET_TRANSACTIONS',
  ADD_JOBS: 'ADD_JOBS'
}

export default type
