const type = {
  SEARCH_QUERY: 'SEARCH_QUERY',
  LOGIN_USER: 'LOGIN_USER',
  SET_USERS: 'SET_USERS',
  SET_JOBS: 'SET_JOBS',
  CREATE_ADMIN: 'CREATE_ADMIN',
  SET_USERS_CARD: 'SET_USERS_CARD'
}

export default type
